name: Build page Workflow
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.0"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r ./docs/requirements.txt

      - uses: actions/cache@v4.1.1
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: List files in the repository
        run: |
            ls ${{ github.workspace }}

      - run: mkdocs gh-deploy --force --config-file ./docs-public/mkdocs.yml
